import { Router } from "express";
import * as c from "../controllers/maintenance.controller";
import { authorize } from "../middleware/authorize";
import { validateBody } from "../middleware/validation.middleware";
import { maintenanceRequestCreateSchema, maintenanceRequestUpdateSchema, maintenanceAssignSchema, maintenanceCostCreateSchema } from "../schemas/maintenance.schema";

const r = Router();
r.get("/", authorize("maintenance", "view"), c.list);
r.post("/", authorize("maintenance", "create"), validateBody(maintenanceRequestCreateSchema), c.create);
r.get("/:id", authorize("maintenance", "view"), c.get);
r.patch("/:id", authorize("maintenance", "update"), validateBody(maintenanceRequestUpdateSchema), c.update);
r.post("/:id/assign", authorize("maintenance", "update"), validateBody(maintenanceAssignSchema), c.assign);
r.post("/:id/start", authorize("maintenance", "update"), c.start);
r.post("/:id/complete", authorize("maintenance", "update"), c.complete);
r.post("/:id/cancel", authorize("maintenance", "update"), c.cancel);
r.delete("/:id", authorize("maintenance", "delete"), c.remove);
r.get("/:requestId/costs", authorize("maintenance", "view"), c.listCosts);
r.post("/:requestId/costs", authorize("maintenance", "update"), validateBody(maintenanceCostCreateSchema), c.addCost);
r.delete("/costs/:id", authorize("maintenance", "update"), c.removeCost);
export default r;
